title: coatl.dev Formulae
description: coatl-dev's Homebrew package index

remote_theme: Homebrew/brew.sh

exclude:
  - script
  - CNAME
  - README.md
  - Gemfile*

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      image: assets/coatl.png
      search_name: Homebrew Formulae
      search_site: formulae

taps:
  coatl-dev:
    repo: coatl-dev
    name: coatl-dev/coatl-dev
    fullname: coatl-dev/homebrew-coatl-dev
    remote: https://github.com/coatl-dev/homebrew-coatl-dev
    api: https://formulae.coatl.dev/api
    bottle_dir: bottle
    formula_dir: formula
  core:
    repo: core
    name: Homebrew/core
    fullname: Homebrew/homebrew-core
    remote: https://github.com/Homebrew/homebrew-core
    api: https://formulae.coatl.dev/api
    bottle_dir: bottle-core
    formula_dir: formula-core

logo: assets/coatl.png

forkme_nwo: coatl-dev/formulae.coatl.dev

twitter:
  username: __coatldev__
