name: Generate site

on:
  workflow_dispatch:

jobs:
  generate-site:
    runs-on: ubuntu-latest

    container: ghcr.io/homebrew/brew:3.6.21

    steps:
      - uses: actions/checkout@v4

      - run: |
          ./script/generate-core.rb

      - run: |
          ./script/generate.rb

      - run: |
          git status -s
