name: generate-site

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/homebrew/brew:3.6.21
      options: --user root
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v4

      - run: |
          git config --global --add safe.directory "${PWD}"

      - run: |
          brew tap coatl-dev/coatl-dev

      - run: |
          ./script/generate.rb

      - run: |
          ./script/generate-core.rb

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: '.'

  create-pr:
    runs-on: ubuntu-20.04
    needs: generate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Detect changes
        id: git-diff
        uses: coatl-dev/actions/simple-git-diff@v0

      - name: Import GPG key
        if: ${{ success() && steps.git-diff.outputs.diff == 'true' }}
        id: gpg-import
        uses: coatl-dev/actions/gpg-import@v0
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - name: Create Pull Request if changes were detected
        if: ${{ success() && steps.git-diff.outputs.diff == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
        run: |
          git checkout -B coatl-bot-docs-autoupdate
          git add --all
          git commit -m "docs: update docs"
          git push --force --set-upstream origin coatl-bot-docs-autoupdate
          gh pr create --fill
