name: generate-site

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v4

      - run: |
          make all

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            ${{ github.workspace }}
            !.git/
            !.github/

  create-pr:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v4

      - run: |
          rm -r \
            _data \
            api \
            formula

      - uses: actions/download-artifact@v4
        with:
          name: site

      - uses: coatl-dev/actions/simple-git-diff@v3
        id: git-diff

      - if: ${{ steps.git-diff.outputs.diff == 'true' }}
        uses: coatl-dev/actions/gpg-import@v3
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          git checkout -B coatl-bot-docs-autoupdate
          git add --all
          git commit -m "docs: update docs"
          git push --force --set-upstream origin coatl-bot-docs-autoupdate

      - if: ${{ steps.git-diff.outputs.diff == 'true' }}
        uses: coatl-dev/actions/pr-create@v3
        with:
          gh-token: ${{ secrets.COATL_BOT_GH_TOKEN }}
