name: generate-site

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/homebrew/brew:3.6.21
      options: --user root
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v4

      - run: |
          brew tap coatl-dev/coatl-dev

      - run: |
          ./script/generate.rb

      - run: |
          ./script/generate-core.rb

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: |
            ${{ github.workspace }}
            !.git/
            !.github/

  create-pr:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v4

      - run: |
          rm -r _data
          rm -r api
          rm -r formula
          rm -r formula-core

      - uses: actions/download-artifact@v3
        with:
          name: site

      - uses: coatl-dev/actions/simple-git-diff@v0
        id: git-diff

      - uses: coatl-dev/actions/gpg-import@v0
        if: ${{ success() && steps.git-diff.outputs.diff == 'true' }}
        with:
          passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
          private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}

      - run: |
          git checkout -B coatl-bot-docs-autoupdate
          git add --all
          git commit -m "docs: update docs"
          git push --force --set-upstream origin coatl-bot-docs-autoupdate
          gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
        if: ${{ success() && steps.git-diff.outputs.diff == 'true' }}
