on:
  workflow_dispatch:

jobs:
  generate-site:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/homebrew/brew:3.6.21
      options: --user root
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v4

      - run: |
          brew tap coatl-dev/coatl-dev

      - run: |
          ./script/generate-core.rb

      - run: |
          ./script/generate.rb

      - run: |
          git status -s
