name: Generate site

on:
  workflow_dispatch:

jobs:
  generate-site:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use brew<4
        run: |
          cd "$(brew --prefix)"
          git checkout 3.6.21
          pushd

      - run: |
          ./script/generate-core.rb

      - run: |
          ./script/generate.rb

      - run: |
          git status -s
